# Generated by Django 2.1.2 on 2018-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_acron',
            field=models.CharField(default=1, max_length=2, verbose_name='Category acronym'),
            preserve_default=False,
        ),
    ]
