# Generated by Django 2.1 on 2018-09-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0004_remove_income_user'),
        ('login', '0002_auto_20180829_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klee_income.Income'),
            preserve_default=False,
        ),
    ]
