# Generated by Django 2.1 on 2018-09-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_profile_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='income',
        ),
    ]
