# Generated by Django 2.1.2 on 2018-10-09 23:19

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0002_auto_20181009_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('R$', 'Real')], default='BRL', editable=False, max_length=3),
        ),
    ]
