# Generated by Django 2.1.2 on 2018-10-09 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0003_auto_20181009_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 10, 9, 23, 57, 20, 498950)),
        ),
    ]
