# Generated by Django 2.1 on 2018-09-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0003_auto_20180927_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor'),
        ),
    ]
