# Generated by Django 2.1 on 2018-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0004_auto_20180927_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='consumption_opts',
            field=models.CharField(choices=[('S', 'SEMANAL'), ('M', 'MENSAL')], default='S', max_length=1, verbose_name='Consumption type'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
