# Generated by Django 2.1.2 on 2018-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0004_auto_20181009_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(),
        ),
    ]
