# Generated by Django 2.1.2 on 2018-10-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0005_auto_20181009_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='category_opts',
            field=models.CharField(choices=[('OT', 'OTHERS'), ('NC', 'NO CATEGORY'), ('HM', 'HOME'), ('ET', 'EDUCATION'), ('RT', 'RECREATION'), ('FD', 'FOOD'), ('TP', 'TRANSPORT'), ('PE', 'PERSONAL EXPENSES'), ('CM', 'COMMUNICATION'), ('RT', 'RATES AND TAXES'), ('HT', 'HEALTH')], default='NC', max_length=2, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='consumption_opts',
            field=models.CharField(choices=[('S', 'SEMANAL'), ('M', 'MENSAL')], default='S', max_length=1, verbose_name='Expense type'),
        ),
    ]
