# Generated by Django 2.1.2 on 2018-10-16 00:27

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0011_auto_20181014_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='BRL', max_digits=14),
        ),
    ]
