# Generated by Django 2.1.2 on 2018-10-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0012_auto_20181016_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='consumption',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klee_consumption.Category'),
            preserve_default=False,
        ),
    ]
