# Generated by Django 2.1.2 on 2018-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0013_auto_20181016_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='category',
            field=models.CharField(choices=[('0', 'Teste'), ('1', 'Category')], default=1, max_length=1, verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
