# Generated by Django 2.1.2 on 2018-10-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0014_auto_20181016_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='category_opts',
        ),
    ]
