# Generated by Django 2.1.2 on 2018-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0015_remove_consumption_category_opts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='category',
            field=models.CharField(default=1, max_length=1, verbose_name='Category'),
        ),
    ]
