# Generated by Django 2.1.2 on 2018-10-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0016_auto_20181016_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klee_category.Category'),
        ),
    ]
