# Generated by Django 2.1.2 on 2018-10-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0017_auto_20181016_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, related_name='system_category', to='klee_category.Category'),
        ),
    ]
