# Generated by Django 2.1.2 on 2018-10-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_consumption', '0019_auto_20181028_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_category', to='klee_category.Category'),
        ),
    ]
