# Generated by Django 2.1 on 2018-09-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
