# Generated by Django 2.1 on 2018-09-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0003_auto_20180914_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
    ]
