# Generated by Django 2.1 on 2018-09-26 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0005_income_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
