# Generated by Django 2.1 on 2018-09-27 04:43

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0010_auto_20180927_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='EUR', max_digits=14),
        ),
        migrations.AlterField(
            model_name='income',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'BRL R$')], default='EUR', editable=False, max_length=3),
        ),
    ]
