# Generated by Django 2.1.2 on 2018-10-09 23:19

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('klee_income', '0011_auto_20180927_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default=Decimal('0.0'), default_currency='BRL', max_digits=14),
        ),
        migrations.AlterField(
            model_name='income',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('R$', 'Real')], default='BRL', editable=False, max_length=3),
        ),
    ]
